# For more details on how to configure Wrangler, refer to:
# https://developers.cloudflare.com/workers/wrangler/configuration/

name = "linkblog-email-connector"
main = "src/index.ts"
compatibility_date = "2025-07-15"
compatibility_flags = [ "nodejs_compat" ]

[observability]
enabled = true

[vars]
GITHUB_REPO = "rmeno12.github.io"
GITHUB_USER = "rmeno12"
